require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - Gemfile
    - config.ru
    - Rakefile
    - vendor/**/*
  TargetRubyVersion: 3.1.1
  TargetRailsVersion: 7.0.2.3
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
